### ISSUE TITLE
QUnit Tests no.s 4 & 6 fail 

### ISSUE THREAD

**Issue by lucyrose93** [FAC10/week3-Facalacalaca#81]
Your QUnit tests look good at first glance. But tests 4 and 6 fail. You may have already considered this but it might be worth refactoring before the presentation

**Comment by ZooeyMiller** [comment]
Test 4 fails due to the expected result being different from what you return in your script.js.

![test-mistake](https://cloud.githubusercontent.com/assets/21139983/23791825/7114821a-057c-11e7-9873-92af02f55521.png)


On the left is your tests.js file, you expect the appended part of the url string to be "Jurassic%20Park", but on the right in your script.js you append both the argument "movie" with URI encoding and the word "film". If you add "film" to the end of the expected string the test should pass.
